//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP_FingerPrint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinh
    {
        public int ID { get; set; }
        public string Absent { get; set; }
        public string Attend { get; set; }
        public int IDtk { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
